server.port=8081
spring.application.name=API-Gateway
spring.cloud.gateway.discovery.locator.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# 1. Ruta Clientes
spring.cloud.gateway.routes[0].id=clientes-service
spring.cloud.gateway.routes[0].uri=lb://clientes-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/clientes/**

# 2. Ruta Citas
spring.cloud.gateway.routes[1].id=citas-service
spring.cloud.gateway.routes[1].uri=lb://citas-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/citas/**

# 3. Ruta Vehículos
spring.cloud.gateway.routes[2].id=vehiculos-service
spring.cloud.gateway.routes[2].uri=lb://vehiculos-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/vehiculos/**

# 4. Ruta Inventario
spring.cloud.gateway.routes[3].id=inventario-service
spring.cloud.gateway.routes[3].uri=lb://inventario-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/inventario/**

# 5. Ruta Reparaciones
spring.cloud.gateway.routes[4].id=reparaciones-service
spring.cloud.gateway.routes[4].uri=lb://reparaciones-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/reparaciones/**

# 6. Ruta Estética
spring.cloud.gateway.routes[5].id=estetica-service
spring.cloud.gateway.routes[5].uri=lb://estetica-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/v1/estetica/**

# 7. Ruta Facturación
spring.cloud.gateway.routes[6].id=facturacion-service
spring.cloud.gateway.routes[6].uri=lb://facturacion-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/v1/facturacion/**

# 8. Ruta Proveedores
spring.cloud.gateway.routes[7].id=proveedores-service
spring.cloud.gateway.routes[7].uri=lb://proveedores-service
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/v1/proveedores/**

# 9. Ruta Notificaciones
spring.cloud.gateway.routes[8].id=notificaciones-service
spring.cloud.gateway.routes[8].uri=lb://notificaciones-service
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/v1/notificaciones/**

# 10. Ruta Reseñas
spring.cloud.gateway.routes[9].id=resenas-service
spring.cloud.gateway.routes[9].uri=lb://resenas-service
spring.cloud.gateway.routes[9].predicates[0]=Path=/api/v1/resenas/**
